### ISSUE TITLE
Error run "simple_extractor.py"

### ISSUE THREAD

**Issue by sajjadaemmi** [PeikeLi/Self-Correction-Human-Parsing#18]
i run this command:
`python simple_extractor.py --dataset pascal --model-restore models/exp-schp-201908270938-pascal-person-part.pth --input input --output output --logits`
and get this error:
```
C:\Users\deep1\anaconda3\envs\PressureUlcer\lib\site-packages\torch\utils\cpp_extension.py:189: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
INFO: Could not find files for the given pattern(s).
Traceback (most recent call last):
  File "simple_extractor.py", line 24, in <module>
    import networks
  File "D:\Deep1\Projects\pressure-ulcer\Self-Correction-Human-Parsing\networks\__init__.py", line 3, in <module>
    from networks.AugmentCE2P import resnet101
  File "D:\Deep1\Projects\pressure-ulcer\Self-Correction-Human-Parsing\networks\AugmentCE2P.py", line 21, in <module>
    from modules import InPlaceABNSync
  File "D:\Deep1\Projects\pressure-ulcer\Self-Correction-Human-Parsing\modules\__init__.py", line 1, in <module>
    from .bn import ABN, InPlaceABN, InPlaceABNSync
  File "D:\Deep1\Projects\pressure-ulcer\Self-Correction-Human-Parsing\modules\bn.py", line 10, in <module>
    from modules.functions import *
  File "D:\Deep1\Projects\pressure-ulcer\Self-Correction-Human-Parsing\modules\functions.py", line 18, in <module>
    extra_cuda_cflags=["--expt-extended-lambda"])
  File "C:\Users\deep1\anaconda3\envs\PressureUlcer\lib\site-packages\torch\utils\cpp_extension.py", line 658, in load
    is_python_module)
  File "C:\Users\deep1\anaconda3\envs\PressureUlcer\lib\site-packages\torch\utils\cpp_extension.py", line 827, in _jit_compile
    with_cuda=with_cuda)
  File "C:\Users\deep1\anaconda3\envs\PressureUlcer\lib\site-packages\torch\utils\cpp_extension.py", line 876, in _write_ninja_file_and_build
    with_cuda=with_cuda)
  File "C:\Users\deep1\anaconda3\envs\PressureUlcer\lib\site-packages\torch\utils\cpp_extension.py", line 1089, in _write_ninja_file
    'cl']).decode().split('\r\n')
  File "C:\Users\deep1\anaconda3\envs\PressureUlcer\lib\subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "C:\Users\deep1\anaconda3\envs\PressureUlcer\lib\subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1.
```

before recent updates, i could run 
`python evaluate.py --dataset pascal --restore-weight models/exp-schp-201908270938-pascal-person-part.pth --input input --output output --logits`
in old code and it works!

My environment :
torch : 1.2.0
os : windows 10
python 3.6

**Comment by PeikeLi** [comment]
The error was caused by the compiling of InplaceSyncBN. Seems the issue you raised tight with your specific env configuration and I was not able to reproduce it from my side. For me, it works well on Linux.

Here are some suggestions:
1) Try change the version of PyTorch. 
2) Refer to InplaceSyncBN https://github.com/mapillary/inplace_abn for similar errors.
3) Try on Linux.

**Comment by sajjadaemmi** [comment]
i tried your suggestions, run on linux worked for me. thanks

**Comment by soumyajit123dev** [comment]
> i tried your suggestions, run on linux worked for me. thanks

I got similar error. Please can you tell how you solved it. Btw, I am using ubuntu only. still it is not working for me. When I run simple_extractor.py, I get same error message plus some extra errors also which is like

ninja: build stopped: subcommand failed.

**Comment by SajjadAemmi** [comment]
@soumyajit123dev what is your PyTorch version?
did you install inplace_abn?

**Comment by parakh08** [comment]
I have torch 1.5.1 and python 3.8.5, have installed inplace_abn in my conda environment.
I am still facing this issue while trying to run simple_extractor.py .
Can you help me in this?

**Comment by SajjadAemmi** [comment]
@parakh08 
Try on Linux

**Comment by parakh08** [comment]
I am trying on ubuntu only.

**Comment by SajjadAemmi** [comment]
@parakh08 
change the version of PyTorch. try 1.8 or 1.9
