### ISSUE TITLE
setup.py and .pth

### ISSUE THREAD

**Issue by yunshangyue71** [PeikeLi/Self-Correction-Human-Parsing#19]
I find there is no setup.py and the pre_trained model which you offer is not match the network.

**Comment by PeikeLi** [comment]
1) The current code base adopts the implementation of InplaceSyncBN from https://github.com/mapillary/inplace_abn. The compiling of the InplaceSyncBN operator will be automatically triggered when running the code.

2) Our former codebase is based on PyTorch version 0.4. However, we have upgraded to pytorch>1.0 for simplicity usage.
From my side, the current provided pre-trained model matches the network configuration. Please clarify what kind of mismatch.

**Comment by yunshangyue71** [comment]
**After killing several bugs that produced by my environment.The major bug apper.**
(pytorch15) q30004136:~/SCHP_org$ python train.py
Traceback (most recent call last):
  File "train.py", line 25, in <module>
    import networks
  File "/data_ssd3/q30004136/SCHP_org/networks/__init__.py", line 3, in <module>
    from networks.AugmentCE2P import resnet101
  File "/data_ssd3/q30004136/SCHP_org/networks/AugmentCE2P.py", line 21, in <module>
    from modules import InPlaceABNSync
  File "/data_ssd3/q30004136/SCHP_org/modules/__init__.py", line 1, in <module>
    from .bn import ABN, InPlaceABN, InPlaceABNSync
  File "/data_ssd3/q30004136/SCHP_org/modules/bn.py", line 10, in <module>
    from .functions import *
  File "/data_ssd3/q30004136/SCHP_org/modules/functions.py", line 18, in <module>
    extra_cuda_cflags=["--expt-extended-lambda"])
  File "/data_ssd3/q30004136/anaconda3/envs/pytorch15/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 921, in load
    is_python_module)
  File "/data_ssd3/q30004136/anaconda3/envs/pytorch15/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1120, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/data_ssd3/q30004136/anaconda3/envs/pytorch15/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1441, in _import_module_from_library
    file, path, description = imp.find_module(module_name, [path])
  File "/data_ssd3/q30004136/anaconda3/envs/pytorch15/lib/python3.7/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
**ImportError: No module named 'inplace_abn'**
(pytorch15) q30004136:~/SCHP_org$

**my environment is CUDA 10.2 ,ubuntu 18.0.4,python3.7**
The error is  there is no inplace_abn model .Do i need download the inplace_abn from  https://github.com/mapillary/inplace_abn
and then put into the project?
when i run this command ：pip install inplace_abn.it says that: Requirement already satisfied: inplace_abn in /data_ssd3/q30004136/anaconda3/envs/pytorch15/lib/python3.7/site-packages/inplace_abn-0.0.0-py3.7-linux-x86_64.egg (0.0.0)

i don't kown how to solve this problem. I need your help please.

**Comment by PeikeLi** [comment]
You don't need to install inplace_abn by yourself. The current code base already contains the inplace_abn implementation in ./modules. And the compiling of the InplaceSyncBN operator will be automatically triggered when running the code.

**Comment by yunshangyue71** [comment]
I have tried several times ，it always the same error.
---------------------------
File "/data_ssd3/q30004136/SCHP_org/modules/functions.py", line 18, in
extra_cuda_cflags=["--expt-extended-lambda"])
ImportError: No module named 'inplace_abn'
---------------------------
How do i solve this problem？thank you very much！

**Comment by amandazw** [comment]
@yunshangyue71 ImportError: No module named 'inplace_abn' did you solve this？

**Comment by Xuan266** [comment]
I met the same problem,have you solved it? my environment is cuda11.2 , pytorch 1.5.1
`envs/schp/lib/python3.8/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'inplace_abn'
`

**Comment by ErfanMomeniii** [comment]
The inplace_abn has many problems with versions of pytorch and cuda and the environment. Can we use some alternatives for that? For example, replace InPlaceABNSync with nn.BatchNorm2d and nn.ReLU to save functionality and fix the problem.
Did anyone try to do that?

**Comment by yunshangyue71** [comment]
> The inplace_abn has many problems with versions of pytorch and cuda and the environment. Can we use some alternatives for that? For example, replace InPlaceABNSync with nn.BatchNorm2d and nn.ReLU to save functionality and fix the problem. Did anyone try to do that?

if you retrain the model I think  nn.BatchNorm2d is and relu are ok。if you use the ckpt to predict, I think  nn.BatchNorm2d is ok. Because InPlaceABNSync is nn.BatchNorm2d used by multi GPUs. perhaps the method is do  nn.BatchNorm2d in each GPU, and return the means and norms， then get the total BN in the master GPU。 so i think replace InPlaceABNSync with nn.BatchNorm2d is ok. 

I have tested this model on life and office sence pictures，eg. holding a pad in front of my chest, a part of my body covered by desk. I think there still a lot of room for improvement.

have you tried a light model trained by Apple or Google.Im not mean there are better but give you more choice.
you can alse follow some works about MPI.
