### ISSUE TITLE
Error when training with torch 1.5.1

### ISSUE THREAD

**Issue by usernameandme** [PeikeLi/Self-Correction-Human-Parsing#21]
There are some additional checks added in the pytorch framework which is causing the error when running the training script with torch 1.5.1. With torch version 1.2.0 training proceeds without error.

https://github.com/pytorch/pytorch/commit/3e8d8132638c47d3093cc3d8ca7e47a29a4e5818

python train.py --gpu 0

Traceback (most recent call last):
  File "train.py", line 231, in <module>
    main()
  File "train.py", line 178, in main
    preds = model(images)
  File "/home/xxx/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xxx/miniconda3/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/xxx/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xxx/Self-Correction-Human-Parsing/networks/AugmentCE2P.py", line 298, in forward
    x = self.relu1(self.bn1(self.conv1(x)))
  File "/home/xxx/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xxx/Self-Correction-Human-Parsing/modules/bn.py", line 119, in forward
    self.training, self.momentum, self.eps, self.activation, self.slope)
RuntimeError: Some elements marked as dirty during the forward method were not returned as output. The inputs that are modified inplace must all be outputs of the Function.

**Comment by PeikeLi** [comment]
I suppose this error is accompanied by different PyTorch versions and caused by the implementation of InplaceABN.

In order to upgrade to pytorch>1.0, we adopt [InplaceABN v0.1](the https://github.com/mapillary/inplace_abn/tree/v0.1), which works well on most PyTorch versions.

**Comment by usernameandme** [comment]
Created Pull request: https://github.com/PeikeLi/Self-Correction-Human-Parsing/pull/22, please review.
