### ISSUE TITLE
no response in train.py 

### ISSUE THREAD

**Issue by sajjadaemmi** [PeikeLi/Self-Correction-Human-Parsing#29]
I tried to train on a custom data set for human parsing. code run until this line: 
`for i_iter, batch in enumerate(train_loader):`
and It gets pause in this line and the code does not continue to run. 
maybe train_loader object is my problem!?
and after i stop the code manually, show this message:

```
Traceback (most recent call last):
  File "train.py", line 245, in <module>
    main()
  File "train.py", line 152, in main
    for i_iter, batch in enumerate(train_loader):
  File "/home/deep1/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/deep1/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 841, in _next_data
    idx, data = self._get_data()
  File "/home/deep1/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 798, in _get_data
    success, data = self._try_get_data()
  File "/home/deep1/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 761, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/home/deep1/anaconda3/envs/PressureUlcer/lib/python3.6/queue.py", line 173, in get
    self.not_empty.wait(remaining)
  File "/home/deep1/anaconda3/envs/PressureUlcer/lib/python3.6/threading.py", line 299, in wait
    gotit = waiter.acquire(True, timeout)

```

**Comment by sajjadaemmi** [comment]
my problem was **num_workers** parameter in **train_loader = data.DataLoader(...)**
i comment that and code worked
