### ISSUE TITLE
ImportError: /tmp/torch_extensions/inplace_abn/inplace_abn.so: undefined symbol: _ZN3c104impl25tls_local_tensor_type_setEv

### ISSUE THREAD

**Issue by rkhilnani9** [PeikeLi/Self-Correction-Human-Parsing#32]
Using torch==1.4.0 and torchvision==0.4.0.

In train.py, getting the following error - 

Traceback (most recent call last):
  File "train.py", line 25, in <module>
    import networks
  File "/rapids/notebooks/atcdata/rkhilnan/Self-Correction-Human-Parsing/networks/__init__.py", line 3, in <module>
    from networks.AugmentCE2P import resnet101
  File "/rapids/notebooks/atcdata/rkhilnan/Self-Correction-Human-Parsing/networks/AugmentCE2P.py", line 21, in <module>
    from modules import InPlaceABNSync
  File "/rapids/notebooks/atcdata/rkhilnan/Self-Correction-Human-Parsing/modules/__init__.py", line 1, in <module>
    from .bn import ABN, InPlaceABN, InPlaceABNSync
  File "/rapids/notebooks/atcdata/rkhilnan/Self-Correction-Human-Parsing/modules/bn.py", line 10, in <module>
    from .functions import *
  File "/rapids/notebooks/atcdata/rkhilnan/Self-Correction-Human-Parsing/modules/functions.py", line 18, in <module>
    extra_cuda_cflags=["--expt-extended-lambda"])
  File "/conda/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 658, in load
    is_python_module)
  File "/conda/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 838, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/conda/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 982, in _import_module_from_library
    return imp.load_module(module_name, file, path, description)
  File "/conda/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/conda/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)

**Comment by rkhilnani9** [comment]
Apologies. Using torch==1.2.0

**Comment by VyBui** [comment]
@rkhilnani9  I have got the same issue, but when I switched to use torch 1.5.1, torchvision 0.6.1. The issue no longer exists.

**Comment by rkhilnani9** [comment]
@VyBui Thanks! That error is no longer there and I am almost able to train the model.

Faced another error in train.py though. Would you happen to know anything about this?

Traceback (most recent call last):
  File "train.py", line 231, in <module>
    main()
  File "train.py", line 94, in main
    AugmentCE2P = networks.init_model(args.arch, num_classes=args.num_classes, pretrained=args.imagenet_pretrain)  File "/rapids/notebooks/atcdata/rkhilnan/Self-Correction-Human-Parsing/networks/__init__.py", line 13, in init_model    return __factory[name](*args, **kwargs)
  File "/rapids/notebooks/atcdata/rkhilnan/Self-Correction-Human-Parsing/networks/AugmentCE2P.py", line 336, in resnet101
    initialize_pretrained_model(model, settings, pretrained)
  File "/rapids/notebooks/atcdata/rkhilnan/Self-Correction-Human-Parsing/networks/AugmentCE2P.py", line 330, in initialize_pretrained_model
    model.load_state_dict(new_params)
  File "/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 847, in load_state_dict    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ResNet:
        Unexpected key(s) in state_dict: "state_dict".

**Comment by rkhilnani9** [comment]
So I want to try out the exp-schp-pascal-person.pth model, and I have downloaded the weights and saved it in pretrained_model folder inside my repo. Do I also have to download resnet-101.pth?

**Comment by VyBui** [comment]
@rkhilnani9 I have not seen that error yet.

Yes, you have to download resnet101-imagenet.pth and place it in the `pretrained_model`
