### ISSUE TITLE
Training errors  on LIP 

### ISSUE THREAD

**Issue by abhigoku10** [PeikeLi/Self-Correction-Human-Parsing#68]
@PeikeLi @usernameandme  thanks for the sharing the code base , i am getting the follwoing error when i am trying to replicated the results for the LIP dataset
"Traceback (most recent call last):
  File "train.py", line 233, in <module>
    main()
  File "train.py", line 190, in main
    soft_edge.append(soft_pred[1][-1])
IndexError: list index out of range"

from schp_1_checkpoint.pth.tar during the cycle training i am getting this error

**Comment by amcs-echo-0** [comment]
Hello, I have met the same error, have you figured it out?

**Comment by KudoKhang** [comment]
![image](https://user-images.githubusercontent.com/24488797/170006165-1a298bbe-3c0f-4de2-aef4-b5502d978425.png)
You can try my [code!](https://github.com/KudoKhang/Human-Parsing/blob/master/train.py)

**Comment by amcs-echo-0** [comment]
> ![image](https://user-images.githubusercontent.com/24488797/170006165-1a298bbe-3c0f-4de2-aef4-b5502d978425.png) You can try my [code!](https://github.com/KudoKhang/Human-Parsing/blob/master/train.py)

thanks for your reply! I'll try it later. : )

**Comment by duACGN** [comment]
> ![image](https://user-images.githubusercontent.com/24488797/170006165-1a298bbe-3c0f-4de2-aef4-b5502d978425.png) You can try my [code!](https://github.com/KudoKhang/Human-Parsing/blob/master/train.py)

你好，我能问一个简单的问题吗，请问您知道作者这里原代码的真正用意是什么吗，我看你改的代码只适用于batch size = 2 的情况
Hello, can I ask you a simple question? Do you know what the author's original code really means? I think the code you changed is only applicable to batch size=2
